Watashitatihatuyoi/nagano_cake

Gemfile
Gemfile.lock
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
config/initializers/kaminari_config.rb

gem kaminariを追加しました。ページネーションです。

[Add]gem-kaminari

---

app/javascript/packs/application.js
app/javascript/stylesheets/application.scss
app/views/layouts/application.html.erb
config/webpack/environment.js
package.json
yarn.lock

ブートストラップを導入しました。application.html.erb内の記述はハマーがやります。

Feature install bootstrap

---

Gemfile
Gemfile.lock

[Add]gem enum_help

---

app/models/customer.rb
config/routes.rb
db/migrate/20230817081651_devise_create_customers.rb
db/schema.rb
test/fixtures/customers.yml
test/models/customer_test.rb

[Add]customer-model

---

app/models/address.rb
db/migrate/20230817082823_create_addresses.rb
db/schema.rb
test/fixtures/addresses.yml
test/models/address_test.rb

[Add]address-model

---

app/models/genre.rb
db/migrate/20230817085044_create_genres.rb
db/schema.rb
test/fixtures/genres.yml
test/models/genre_test.rb

[Add]genre-model

---

app/models/cart_item.rb
db/migrate/20230817090042_create_cart_items.rb
db/schema.rb
test/fixtures/cart_items.yml
test/models/cart_item_test.rb

[Add]cart_item-model

---

app/models/order.rb
db/migrate/20230817090805_create_orders.rb
db/schema.rb
test/fixtures/orders.yml
test/models/order_test.rb

[Add]order-model

---

app/models/order_item.rb
db/migrate/20230817091926_create_order_items.rb
db/schema.rb
test/fixtures/order_items.yml
test/models/order_item_test.rb

[Add]order_item-model

---

app/controllers/admin/confirmations_controller.rb
app/controllers/admin/omniauth_callbacks_controller.rb
app/controllers/admin/passwords_controller.rb
app/controllers/admin/registrations_controller.rb
app/controllers/admin/sessions_controller.rb
app/controllers/admin/unlocks_controller.rb

[Add]admin-controller

---

app/controllers/public/confirmations_controller.rb
app/controllers/public/omniauth_callbacks_controller.rb
app/controllers/public/passwords_controller.rb
app/controllers/public/registrations_controller.rb
app/controllers/public/sessions_controller.rb
app/controllers/public/unlocks_controller.rb

[Add]customer-controller

---

app/assets/stylesheets/public/addresses.scss
app/assets/stylesheets/public/cart_items.scss
app/assets/stylesheets/public/customers.scss
app/assets/stylesheets/public/homes.scss
app/assets/stylesheets/public/items.scss
app/assets/stylesheets/public/orders.scss
app/controllers/public/addresses_controller.rb
app/controllers/public/cart_items_controller.rb
app/controllers/public/customers_controller.rb
app/controllers/public/homes_controller.rb
app/controllers/public/items_controller.rb
app/controllers/public/orders_controller.rb
app/helpers/public/addresses_helper.rb
app/helpers/public/cart_items_helper.rb
app/helpers/public/customers_helper.rb
app/helpers/public/homes_helper.rb
app/helpers/public/items_helper.rb
app/helpers/public/orders_helper.rb
test/controllers/public/addresses_controller_test.rb
test/controllers/public/cart_items_controller_test.rb
test/controllers/public/customers_controller_test.rb
test/controllers/public/homes_controller_test.rb
test/controllers/public/items_controller_test.rb
test/controllers/public/orders_controller_test.rb

[Add]controller-public-all

---

app/assets/stylesheets/admin/customers.scss
app/assets/stylesheets/admin/genres.scss
app/assets/stylesheets/admin/homes.scss
app/assets/stylesheets/admin/items.scss
app/assets/stylesheets/admin/order_items.scss
app/assets/stylesheets/admin/orders.scss
app/controllers/admin/customers_controller.rb
app/controllers/admin/genres_controller.rb
app/controllers/admin/homes_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/order_items_controller.rb
app/controllers/admin/orders_controller.rb
app/helpers/admin/customers_helper.rb
app/helpers/admin/genres_helper.rb
app/helpers/admin/homes_helper.rb
app/helpers/admin/items_helper.rb
app/helpers/admin/order_items_helper.rb
app/helpers/admin/orders_helper.rb
test/controllers/admin/customers_controller_test.rb
test/controllers/admin/genres_controller_test.rb
test/controllers/admin/homes_controller_test.rb
test/controllers/admin/items_controller_test.rb
test/controllers/admin/order_items_controller_test.rb
test/controllers/admin/orders_controller_test.rb

admin側にdevise以外のコントローラーをすべて追加しました。

[Add]controller-admin-all

---

app/views/admin/confirmations/new.html.erb
app/views/admin/mailer/confirmation_instructions.html.erb
app/views/admin/mailer/email_changed.html.erb
app/views/admin/mailer/password_change.html.erb
app/views/admin/mailer/reset_password_instructions.html.erb
app/views/admin/mailer/unlock_instructions.html.erb
app/views/admin/passwords/edit.html.erb
app/views/admin/passwords/new.html.erb
app/views/admin/registrations/edit.html.erb
app/views/admin/registrations/new.html.erb
app/views/admin/sessions/new.html.erb
app/views/admin/shared/_error_messages.html.erb
app/views/admin/shared/_links.html.erb
app/views/admin/unlocks/new.html.erb
app/views/public/confirmations/new.html.erb
app/views/public/mailer/confirmation_instructions.html.erb
app/views/public/mailer/email_changed.html.erb
app/views/public/mailer/password_change.html.erb
app/views/public/mailer/reset_password_instructions.html.erb
app/views/public/mailer/unlock_instructions.html.erb
app/views/public/passwords/edit.html.erb
app/views/public/passwords/new.html.erb
app/views/public/registrations/edit.html.erb
app/views/public/registrations/new.html.erb
app/views/public/sessions/new.html.erb
app/views/public/shared/_error_messages.html.erb
app/views/public/shared/_links.html.erb
app/views/public/unlocks/new.html.erb
config/routes.rb

routingの作成
・deviseのエラー回避
・routing-publicの作成
・routing-adminの作成

Feature routing

---

app/models/address.rb
app/models/cart_item.rb
app/models/customer.rb
app/models/genre.rb
app/models/item.rb
app/models/order.rb
app/models/order_item.rb

[Add]association

---

app/views/public/homes/about.html.erb
app/views/public/homes/top.html.erb

[Add]homes-views

---

app/views/layouts/_admin_signed_in.html.erb
app/views/layouts/_customer_signed_in.html.erb
app/views/layouts/_sign_out.html.erb
app/views/layouts/application.html.erb
config/routes.rb

ヘッダーとフッターのビューを作りました。領域が分かりやすいように仮で色分けしています。
残り作業
・ログイン時のルート確認
・管理者ログイン時のルート確認
・ロゴ画像のレスポンシブ対応
・CSS整理

Feature view header footer

---

app/controllers/admin/order_items_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/public/orders_controller.rb
app/models/address.rb
app/models/order.rb
app/models/order_item.rb
app/views/admin/orders/show.html.erb
app/views/public/orders/complete.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/new.html.erb
app/views/public/orders/show.html.erb
config/application.rb
config/locales/devise.ja.yml
config/locales/ja.yml
db/migrate/20230817090805_create_orders.rb
db/migrate/20230817091926_create_order_items.rb

OrderとOrderItemに関わるビューとコントローラーの作成を行いました。バグのフィックスは動作確認ができ次第着手します。

Feature views order

---

app/views/public/customers/edit.html.erb
app/views/public/registrations/new.html.erb

[Fix]customer-registration/customer-edit

---

app/controllers/public/homes_controller.rb
app/views/public/homes/top.html.erb

homes-controllerとtop,aboutのビューがレイアウト含め完成しました。

Feature home

---

app/views/layouts/_customer_signed_in.html.erb

[Fix]about_path-into-my_page_path

---

app/assets/stylesheets/public/items.scss
app/controllers/admin/items_controller.rb
app/controllers/public/items_controller.rb
app/views/admin/items/new.html.erb
app/views/public/items/_genre.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb

・会員側の商品詳細ページの追加
　　レイアウト未着手
・ジャンル検索の部分テンプレート化
・商品新規登録ページの編集

[Add]Customer item show

---

app/views/public/registrations/new.html.erb

新規会員登録にhidden_fieldで会員ステータスをfalseで追加する記述をしました

[Add]public/new_registration_path/f.hidden_field

---

app/controllers/public/cart_items_controller.rb
app/views/public/cart_items/index.html.erb

[Fix]cart_item-bug

---

app/controllers/admin/items_controller.rb
app/views/admin/genres/edit.html.erb
app/views/admin/items/index.html.erb

管理者側の商品一覧ページ、ジャンル編集ページの追加
　レイアウト未実装

Admin genre edit

---

app/controllers/admin/homes_controller.rb
app/controllers/application_controller.rb
app/views/admin/homes/top.html.erb
app/views/admin/sessions/new.html.erb
app/views/layouts/_admin_signed_in.html.erb

adminのログイン画面と注文履歴一覧画面の作成を行いました。

Feature admin views

---

app/controllers/public/homes_controller.rb
app/views/public/homes/top.html.erb

[Add]home-layouts

---

app/controllers/public/orders_controller.rb
app/models/customer.rb
app/models/order.rb
app/views/admin/homes/top.html.erb
app/views/public/orders/confirm.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/new.html.erb
app/views/public/orders/show.html.erb

カスタマー側の注文フォーム完成です。新しい住所から注文したときはaddressテーブルに新規配送先を登録するようにしてあります。また、admin側のtopページでエラーが起きちゃってたので直しました。

Release fix bug hamano 3

---

app/controllers/public/cart_items_controller.rb
app/models/cart_item.rb
app/views/public/cart_items/index.html.erb

[Add]cart_item-layouts

---

app/controllers/public/items_controller.rb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb

会員側、商品一覧と商品詳細ページのレイアウトと詳細ページのバグの修正

layout customer-index-show

---

app/controllers/admin/order_items_controller.rb
app/controllers/admin/orders_controller.rb
app/models/order.rb
app/models/order_item.rb
app/views/admin/homes/top.html.erb
app/views/admin/orders/show.html.erb
app/views/public/orders/new.html.erb

[Fix]admin-order/order-item

---

app/controllers/admin/genres_controller.rb
app/controllers/admin/items_controller.rb
app/views/public/items/index.html.erb

adminコントローラーにbefore actionの記述と、会員側タイピングミスの修正

Admin before action

---

app/controllers/public/homes_controller.rb
app/views/public/homes/top.html.erb

homes-topにジャンル検索の追加とimgをクリックするとその商品の詳細画面に飛ぶようにしました。

[Add]homes-top-layouts

---

app/controllers/admin/customers_controller.rb
app/models/customer.rb
app/views/admin/customers/edit.html.erb
app/views/admin/customers/index.html.erb
app/views/admin/customers/show.html.erb
app/views/public/addresses/edit.html.erb
app/views/public/addresses/index.html.erb
app/views/public/customers/confirm_withdraw.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb
app/views/public/registrations/new.html.erb
app/views/public/sessions/new.html.erb

Feature customer layout

---

app/assets/stylesheets/public/genres.scss
app/controllers/public/genres_controller.rb
app/helpers/public/genres_helper.rb
app/views/admin/items/edit.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb
app/views/public/genres/show.html.erb
app/views/public/items/_genre.html.erb
config/routes.rb
test/controllers/public/genres_controller_test.rb

管理者側レイアウト、ボタンのフリーズ修正
会員側ジャンル検索機能の実装、ジャンル別一覧ページの作成、ジャンルコントローラーの追加

[Add] admin-db

---

app/views/layouts/_admin_signed_in.html.erb
app/views/public/items/show.html.erb

管理者側のheaderの微調整
会員側商品詳細ページの初期値の修正

[fix]header-layout

---

app/views/public/cart_items/index.html.erb

[Add]cart_items-debug

---

app/controllers/admin/sessions_controller.rb

admin-headerのafter_sign_out_path_forの設定を行いました。

[Add]admin-header-debug

---

app/controllers/public/orders_controller.rb
app/views/public/orders/check.html.erb
app/views/public/orders/new.html.erb
config/application.rb
db/schema.rb

[Fix]public-order-bug

---

app/views/layouts/application.html.erb
app/views/public/orders/complete.html.erb

[Fix]layouts

---

app/views/admin/customers/show.html.erb

[Add]layout

---

app/controllers/admin/sessions_controller.rb
app/views/layouts/application.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb

販売停止中商品がカートに入れられてしまう不具合を解消しました。また、ﾌﾗｯｼｭﾒｯｾｰｼﾞの表示位置を直しました

[Fix]item-order_stop-cart_create

---

app/controllers/admin/genres_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/public/items_controller.rb
app/models/genre.rb
app/models/item.rb
app/views/public/items/index.html.erb
db/schema.rb

admin側の新規商品登録画面とジャンル新規登録画面でのエラー解決のための、バリデーションの追加

[Fix]layout/item
